name: Reusable workflow of configuration and dependency installation

inputs:
  APPSETTINGS:
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1.4.0
      with:
        xcode-version: "14.1"

    - name: create-json
      id: create-json
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "AppSettings.json"
        json: ${{ inputs.APPSETTINGS }}
        dir: '../../../'

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "2.7.2"
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        
    - name: update fastlane (fastlane version changes quite frequently, we need to keep updated)
      shell: bash
      run: |
        gem update fastlane
